name: Build MD
on:
#  schedule:
#    - cron: '*/30 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
    contents: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install tjp
              run: cargo install typedoc_json_to_md
            - name: Run tool
              run: tjp_to_md
            - name: Check for modified files
              id: git-check
              run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
            - name: Commit
              if: steps.git-check.outputs.modified == 'true'
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add .
                git commit -m "[deploy] MD docs build"
                git push
