name: Build MD
on:
#  schedule:
#    - cron: '*/30 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
    contents: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install tjp
              run: cargo install typedoc_json_to_md
            - name: Run tool
              run: tjp_to_md
            - name: Check for modified files
              id: git-check
              run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
            - name: Commit
              if: steps.git-check.outputs.modified == 'true'
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add .
                git commit -m "[deploy] MD docs build"
                git push
    update-site:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v4
          with:
            repository: 'devramsean0/DocsSite'
            token: ${{ secrets.TOKEN }}
            path: '.'
        - name: "Init submodule"
          run: git submodule update --init
        - name: "Update the submodule"
          run: git submodule update --remote docs
        - name: Commit & Push
          uses: nick-fields/retry@v2
          with:
            max_attempts: 3
            retry_on: error
            timeout_minutes: 1
            command: |
              cd out
              git add .
              if git diff-index --quiet HEAD --; then
                echo "No changes to commit, exiting with code 0"
                exit 0;
              else
                git config user.name github-actions[bot]
                git config user.email 41898282+github-actions[bot]@users.noreply.github.com
                git config rebase.autostash true
                git config pull.rebase true
                git commit -m "Update docs submodule" || true
                git pull
                git push
              fi
