name: Sync With Site
on:
#  schedule:
#    - cron: '*/30 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  update-site:
    if: contains(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'devramsean0/DocsSite'
          token: ${{ secrets.TOKEN }}
          path: '.'
      - name: "Init submodule"
        run: git submodule update --init
      - name: "Update the submodule"
        run: git submodule update --remote docs
      - name: Commit & Push
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 1
          command: |
            cd out
            git add .
            if git diff-index --quiet HEAD --; then
              echo "No changes to commit, exiting with code 0"
              exit 0;
            else
              git config user.name github-actions[bot]
              git config user.email 41898282+github-actions[bot]@users.noreply.github.com
              git config rebase.autostash true
              git config pull.rebase true
              git commit -m "Update docs submodule" || true
              git pull
              git push
            fi
